language: python
python:
  - "3.5"
  - "3.6"
env:
  - DJANGO=1.8
  - DJANGO=1.10
matrix:
  include:
    - python: "3.6"
      env: DJANGO=1.8
    - python: "3.6"
      env: DJANGO=1.10
    - python: "3.6"
      env: TOXENV="coverage"
# command to install dependencies
install:
  - pip install tox tox-travis coverage coveralls
# command to run tests
script:
  - tox
after_success:
  - bash scripts/coveralls.sh
# containers
sudo: false

